### PR TITLE
GitHub Actions for linting and building each project

### PR DESCRIPTION
**Pull request by tahsintunan**
Addresses this issue: https://github.com/solendprotocol/public/issues/1

### CODE REVIEW

**Comment by 0xripleys** [comment]
@tahsintunan can you make sure the CI runs on _any_ pull request or branch? not just master. thanks!

**Comment by tahsintunan** [comment]
@0xripleys Sure. Made some changes.

**Comment by 0xripleys** [comment]
ah, i think the workflow yml files have to be in the root directory for the github actions to kick off in this pull request. right now the checks aren't running for this PR (but i think they should run if the workflow files are set up correctly)

**Comment by tahsintunan** [comment]
@0xripleys I can move the yaml files to the root directory. In that case, there'll be 2 yaml files, each having path filters.
```yml
on:
  push:
    paths:
    - 'liquidator/**'
  pull_request:
    paths: 
    - 'liquidator/**'
```

**Comment by tahsintunan** [comment]
@0xripleys Moved the actions to the root directory. Seems to be working.

**Comment by 0xripleys** [comment]
On phone but I don't see that the CI ran for this PR. Did it run? I'm expecting some stuff to show up in the "Checks" tab

**Comment by tahsintunan** [comment]
Screenshot from 2022-11-06 21-09-42

Screenshot from 2022-11-06 21-10-21

**Comment by 0xripleys** [comment]
Amazing, thanks! Lgtm

**Pull request merged**
